swagger: "2.0"
info:
  description: ""
  version: "1.0.0"
  title: "Swagger app-crud"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: ""
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "https://localhost:3001"
basePath: "/v2"
tags:
- name: ""
  description: ""
  externalDocs:
    description: ""
    url: ""
- name: ""
  description: ""
schemes:
- "https"
- "http"
paths:
  /customer:
    post:
      tags:
      - ""
      summary: ""
      description: ""
      operationId: ""
      consumes:
      - ""
      - ""
      produces:
      - ""
      - ""
      parameters:
      - in: "body"
        name: "body"
        description: ""
        required: true
        schema:
          $ref: ""
      responses:
        "405":
          description: ""
    put:
      tags:
      - ""
      summary: ""
      description: ""
      operationId: ""
      consumes:
      - ""
      produces:
      - ""
      parameters:
      - in: "body"
        name: "body"
        description: ""
        required: true
        schema:
          $ref: ""
      responses:
        "400":
          description: ""
        "404":
          description: ""
        "405":
          description: ""
  /customer/{id}:
    get:
      tags:
      - ""
      summary: ""
      description: ""
      operationId: ""
      consumes:
      - ""
      produces:
      - ""
      parameters:
      - in: "body"
        name: "body"
        description: ""
        required: true
        schema:
          $ref: ""
      responses:
        "400":
          description: ""
        "404":
          description: ""
        "405":
          description: ""
definitions:
  Customer:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      email:
        type: "string"
      phone:
        type: "string"
      password:
        type: "string"
        description: ""
    xml:
      name: "Customer"
  Banner:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        format: "string"
      image:
        type: "string"
      customerID:
        type: "string"
        format: ""
      endAt:
        type: "string"
        format: "date-time"
      startAt:
        type: "string"
        format: "date-time"
      status:
        type: "boolean"
        description: ""
    xml:
      name: "Banner"
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"